### ISSUE TITLE
KeyError installing ZenPack on Zenoss 5.0.2

### ISSUE THREAD

**Issue by zaidi** [ssplatt/slack-zenoss#3]
Attempting to install the ZenPack on Zenoss 5.0.2 and I keep getting this error:

> [root@host slack-zenoss-master]# serviced service run zope zenpack install ./ZenPacks
> I0510 03:32:25.556414 25453 server.go:341] Connected to the control center at port x.x.x.x:4979
> I0510 03:32:25.718317 25453 server.go:435] Acquiring image from the dfs...
> I0510 03:32:25.720571 25453 server.go:437] Acquired!  Starting shell
> E0510 10:32:26.475346 00001 endpoint.go:514] No proxy for 79h2psfna1sfguugomoa843lb_zproxy - no need to set empty address list
> E0510 10:32:26.477320 00001 endpoint.go:514] No proxy for 79h2psfna1sfguugomoa843lb_localhost_zenhubPB - no need to set empty address list
> Trying to connect to logstash server... 127.0.0.1:5042
> Connected to logstash server.
> 2015-05-10 10:32:34,658 INFO zen.HookReportLoader: Loading reports from /opt/zenoss/Products/ZenPacks/reports
> 2015-05-10 10:32:34,706 ERROR zen.ZenPackCmd: zenpack command failed
> Traceback (most recent call last):
>  File "/opt/zenoss/Products/ZenUtils/zenpack.py", line 800, in <module>
>    zp.run()
>  File "/opt/zenoss/Products/ZenUtils/zenpack.py", line 246, in run
>    self.install(packName)
>  File "/opt/zenoss/Products/ZenUtils/zenpack.py", line 615, in install
>    zp.install(self.app)
>  File "/opt/zenoss/Products/ZenModel/ZenPack.py", line 276, in install
>    loader.load(self, app)
>  File "/opt/zenoss/Products/ZenModel/ZenPackLoader.py", line 319, in load
>    registerSkin(app.zport.dmd, skinsDir)
>  File "/opt/zenoss/Products/ZenUtils/Skins.py", line 66, in registerSkin
>    addDirectoryViews(skinstool, path, dict(**name**=root))
>  File "/opt/zenoss/lib/python2.7/site-packages/Products/CMFCore/DirectoryView.py", line 612, in addDirectoryViews
>    package = getPackageName(_prefix)
>  File "/opt/zenoss/lib/python2.7/site-packages/Products/CMFCore/utils.py", line 867, in getPackageName
>    return getContainingPackage(module)
>  File "/opt/zenoss/lib/python2.7/site-packages/Products/CMFCore/utils.py", line 847, in getContainingPackage
>    mod = sys.modules[name]
> KeyError: 'skins'
> Command returned non-zero exit code 3.  Container not commited.

What am I doing wrong here?

**Comment by ssplatt** [comment]
I just installed it without an issue on Zenoss 5.0.2.  Are you following the steps in the Administration guide? http://wiki.zenoss.org/download/core/docs/Zenoss_Core_Administration_r5.0.0_latest.pdf , go to page 170 and start with "Preparing to install or upgrade a Zenpack".

**Comment by ssplatt** [comment]
I'm going to mark this as closed since I can't reproduce the issue, unless you have some more comments.
